app/models.py
from datetime import datetime
from hashlib import md5

from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app.db import db


class User(UserMixin, db.Model):
    """
    A user of the application
    """
    id = db.Column(db.Integer, primary_key=True)
    social_id = db.Column(db.String(64), nullable=True, unique=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)
    picture_url = db.Column(db.String(200), nullable=True)

    def avatar(self, size):
        if self.picture_url:
            return self.picture_url

        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(
            digest, size)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User: {} {}>'.format(self.id, self.username)

    def __str__(self):
        return '<User: id={} username={}> email={}'.format(self.id, self.username, self.email)

app/support/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired, Length, Email


class FeedbackForm(FlaskForm):
    name = StringField('Name *', validators=[DataRequired(), Length(min=0, max=50)])
    email = StringField('Email *', validators=[DataRequired(), Email()])
    subject = SelectField('Subject *',
                          choices=[('Saying hello', 'hello'), ('Question', 'Question'), ('Support', 'Support'),
                                   ('Feedback', 'Feedback'), ('A joke', 'A joke'), ('Enhancement', 'Enhancement'),
                                   ('Something else', 'Something else')], validators=[DataRequired()])
    message = TextAreaField('Message *', validators=[DataRequired(), Length(min=0, max=500)])
    submit = SubmitField('Say Hello')

    def to_json(self):
        """
        converts the form to a JSON
        the csrt_token is not included in the response
        :return: JSON representing the contents of the form
        :rtype: JSON
        """
        feedback_dict = {'name': self.name.data, 'email': self.email.data, 'subject': self.subject.data,
                         'message': self.message.data}
        return feedback_dict

app/__init__.py
import logging
from logging import config

import yaml

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_cdn import CDN
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_moment import Moment
from flask_wtf.csrf import CSRFProtect

from app.services import utils
from app.db import db, oauth

from config import app_config

migrate = Migrate()
login = LoginManager()
login.login_view = 'main.welcome'
bootstrap = Bootstrap()
moment = Moment()
csrf = CSRFProtect()

cdn = CDN()


def create_app(config_name='default'):
    """
    Starts up the Flask application based on the supplied configuration
    :param config_class: Configuration to start the app with
    :type config_class:
    :return: the Flask app
    :rtype:
    """
    app = Flask(__name__)
    app.config.from_object(app_config[config_name])
    app_config[config_name].init_app(app)

    with open("log_config.yaml", 'rt') as f:
        config_data = yaml.safe_load(f.read())
        config.dictConfig(config_data)

    app.logger = logging.getLogger(app.config['LOGGING_CONFIG'])
    app.logger.error('starting the app')

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    bootstrap.init_app(app)
    moment.init_app(app)
    csrf.init_app(app)
    cdn.init_app(app)

    oauth.init_app(app)
    oauth.register(
        'auth0',
        client_id=app.config['AUTH0_CLIENT_ID'],
        client_secret=app.config['AUTH0_CLIENT_SECRET'],
        api_base_url=app.config['AUTH0_CLIENT_DOMAIN'],
        access_token_url=app.config['AUTH0_CLIENT_DOMAIN'] + '/oauth/token',
        authorize_url=app.config['AUTH0_CLIENT_DOMAIN'] + '/authorize',
        client_kwargs={
            'scope': 'openid profile email',
        },
    )

    from app.errors.handlers import bp as errors_bp
    from app.auth.routes import bp as auth_bp
    from app.main.routes import bp as main_bp
    from app.support.legal_routes import bp as support_bp
    app.register_blueprint(errors_bp)
    app.register_blueprint(auth_bp, url_prefix='/auth')
    app.register_blueprint(main_bp)
    app.register_blueprint(support_bp, url_prefix='/support')

    # this filter allows environment variables to be read inside the jinja templates
    app.jinja_env.filters['get_os_env'] = utils.get_os_env

    from app.models import User

    @login.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    return app

app/main/routes.py
from datetime import datetime

from flask import Blueprint
from flask import render_template, url_for, current_app, send_from_directory, request
from flask_login import current_user, login_required

from app.models import User
from app import db

bp = Blueprint('main', __name__)


@bp.before_request
def before_request():
    """
    Tracks the date/time the user last logged in and used the application
    :return:
    :rtype:
    """
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/welcome', methods=['GET'])
def welcome():
    """
    shows the welcome page
    :return:
    :rtype:
    """
    return render_template('welcome.html', title='Welcome')


@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    """
    shows the user's regular activities in order for them to log it
    :return:
    :rtype:
    """
    return render_template('index.html', title='Home',
                           form_url=url_for('main.index'))


@bp.route('/user')
@login_required
def user():
    """
    shows the user's profile
    :return:
    :rtype:
    """
    my_user = User.query.filter_by(id=current_user.get_id()).first_or_404()

    return render_template('auth/user.html', user=my_user)


@bp.route('/about', methods=['GET'])
def view_about():
    """
    shows the about page
    :return:
    :rtype:
    """
    return render_template('about.html', title="About Flask AWS Template")


@bp.route('/service-worker.js', methods=['GET'])
def service_worker():
    """
    returns the service-work js file that is required to make the app a full PWA one accessible on mobiles
    easiest to serve this at the root of the application, otherwise there are scope problems with the service worker
    and it cannot access other files
    Alternative is to serve it from the static folder but then the proxy (nginx) needs to send a http header
    :return:
    :rtype:
    """
    return current_app.send_static_file('service-worker.js')


@bp.route('/robots.txt')
@bp.route('/sitemap.xml')
def static_from_root():
    """
    serves the static files used by search crawlers
    these are referred to in the base URL but are served from the static folder
    :return:
    :rtype:
    """
    return send_from_directory(current_app.static_folder, request.path[1:])

app/templates/about.html
{% extends "base.html" %}

{% block content %}
    <section id="home" class="d-flex align-items-center position-relative vh-100 cover hero about">

        <div class="container-fluid container-fluid-max">
            <div class="row">
                <div class="col-12 text-center">
                    <blockquote><h1 class="mb-0 text-white">Begin - to begin is half the work, let half still remain; again begin this, and thou wilt have finished.
                    </h1>
                        <footer class="blockquote-footer text-white">Marcus Aurelius</footer>
                    </blockquote>
                </div>
            </div>
    </section>

    <section id="process" class="features">
        <div class="container-fluid container-fluid-max">
            <div class="row justify-content-md-center">
                <div class="col col-md-8 mx-auto">
                    <h1 class="text-center pb-3">About</h1>
                    <p class="text-center pb-3">
                        Life is too short to re-invent the wheel. We just want to crack on and build great products.
                    </p>
                    <hr class="ml-5 mr-5"/>
                    <p class="text-center pb-3">
                        But there is so much to do in addition to the code.
                    </p>
                    <hr class="ml-5 mr-5"/>
                    <p class="text-center pb-3">
                        This is why this template was put together. To make your life (a little) easier by showing you how to write a Python Flask application.
                    </p>
                    <hr class="ml-5 mr-5"/>
                    <p class="text-center pb-3">
                        It can be easily deployed onto AWS.
                    </p>
                    <hr class="ml-5 mr-5"/>
                    <p class="text-center pb-3">
                        And is free to all.
                    </p>
                    <hr class="ml-5 mr-5"/>
                    <p class="text-center pb-3">
                        So enjoy.
                    </p>
                </div>
            </div>
        </div>
    </section>

    {% if current_user.is_anonymous %}
        <section id="sign-up" class="py-5 request-quote bg-lightblue">
            <div class="container-fluid container-fluid-max">
                <div class="row justify-content-center">
                    <div class="col-12 col-md-auto py-3 text-center">
                        <h2 class="mb-0 text-red">Ready to create an account?</h2>
                        <p class="mb-0 h4 text-red font-weight-normal"></p>
                    </div>
                    <div class="col-12 col-md-auto d-flex justify-content-center align-items-center">
                         <a href="{{ url_for('auth.sign_up') }}" class="btn btn-primary my-2">Sign Up For
                            Free</a>
                    </div>
                </div>
            </div>
        </section>
    {% endif %}

{% endblock %}

app/templates/base.html
{% from "macros.html" import nav_link with context %}
{% from "macros.html" import add_google_analytics with context %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% set code | get_os_env('GA_CODE') %}
    {% endset %}
    {{ add_google_analytics(code) }}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:title" content="Flask AWS Template is a starter template for building Flask apps for AWS"/>
    <meta property="og:image" content="{{ url_for('static', filename='img/og-banner.jpg') }}"/>
    <meta property="og:url" content="{{ url_for('main.welcome') }}"/>
    <meta property="og:type" content="website"/>
    <meta property="og:description"
          content="Use this template as a starter for your own Flask based products hosted on AWS"/>

    <meta name="Description"
          content="Use this template as a starter for your own Flask based products hosted on AWS">


    <title>Flask AWS Template</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/general.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/landing_page.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/about.css') }}">

    <script src="{{ url_for('static', filename='js/cookie.js') }}"></script>

    <link rel="manifest" href="/static/manifest.json">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Flask AWS Template">
    <link href="" rel="apple-touch-icon">

    <link rel="apple-touch-icon" href="{{ url_for('static', filename='img/icons/flask-icon-152x152.png') }}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='img/icons/flask-icon-152x152.png') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/icons/flask-icon-180x180.png') }}">
    <link rel="apple-touch-icon" sizes="167x167" href="{{ url_for('static', filename='img/icons/flask-icon-167x167.png') }}">

    <meta name="theme-color" content="#8745a3"/>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/e6fa600115.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/icons/favicon.ico') }}">


</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a id="main" class="navbar-brand" href="{{ url_for('main.welcome') }}"> <img
            src="{{ url_for('static', filename='img/icons/flask-icon-80x80.png') }}"
            alt="logo">&nbsp;&nbsp;&nbsp;Flask AWS Template</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        {% if current_user.is_anonymous %}
            <ul class="navbar-nav ml-auto">
                {{ nav_link('main.view_about', 'About', 'about_link','') }}
                {{ nav_link('support.contact_us', 'Contact Us', 'contact_us_link','fas fa-envelope') }}
                {{ nav_link('auth.oauth_authorize', 'Login', 'login_link','') }}
                {{ nav_link('auth.sign_up', 'Sign Up', 'register_link','') }}
            </ul>
        {% else %}
            <ul class="navbar-nav ml-auto">
                {{ nav_link('main.view_about', 'About', 'about_link','') }}
                {{ nav_link('support.contact_us', 'Contact Us', 'contact_us_link','fas fa-envelope') }}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user" aria-hidden="true"></i>&nbsp;{{ current_user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a id="profile_link" class="dropdown-item"
                           href="{{ url_for('main.user') }}">Profile</a>
                        <a id="logout_link" class="dropdown-item" href="{{ url_for('auth.logout_new') }}">Logout</a>
                    </div>
                </li>
            </ul>
        {% endif %}
    </div>
</nav>
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

<div class="container-fluid container-fluid-max">
    {% block content %}{% endblock %}

    <footer class="pt-3 my-md-4 pt-md-4 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <a href="{{ url_for('main.welcome') }}"><img class="mb-2 max-height:40px"
                                                             src="{{ url_for('static', filename='img/icons/flask-icon-40x40.png') }}" alt="logo"></a>
                <small class="d-block mb-3 text-muted">&copy; 2020</small>

            </div>
            <div class="col-6 col-md">
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{{ url_for('main.welcome') }}">Home</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{{ url_for('support.faq') }}">FAQ</a></li>
                    <li><a class="text-muted" href="{{ url_for('support.contact_us') }}">Contact Us</a></li>
                    <li><a class="text-muted" href="https://headwayapp.co/">Change Log</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{{ url_for('support.disclaimer') }}">Disclaimer</a></li>
                    <li><a class="text-muted" href="{{ url_for('support.privacy') }}">Privacy</a></li>
                </ul>
            </div>
        </div>
         <div class="alert alert-warning alert-dismissible d-none" role="alert" id="cookie_banner">
            <strong>This site uses cookies.</strong> By continuing to use this site, you accept its use of cookies as
            described in our <a class="btn-link" href="{{ url_for('support.cookies') }}">cookie policy</a>.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close cookie banner"
                    id="cookie_accept">
                <span area-hidden="true">&times;</span>
            </button>
        </div>
    </footer>
</div>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.28.0/moment-with-locales.min.js"
            integrity="sha512-kcvf1mExE8WCOLBL5re/9hLUHfaj8+LQrKlupTarmme+rwv8asLK4q6Ge32trTMBElPBP5sll4czZKNvps0VvA=="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.31/moment-timezone.js"
            integrity="sha256-dWmHGsnrX5SD7KolfPMFQCt8DoDmkrAONz+rCsChg9E=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.31/moment-timezone-with-data-2012-2022.min.js"
            integrity="sha256-J3t/BAGqnl57qtjKVL6IipkuPjImp2hkXeiiwNYELLw=" crossorigin="anonymous"></script>
    {{ moment.include_moment(no_js=True) }}
    {# Need to put the moment include back in once it supports forcing of https #}

        <div class="row">
            <div class="col-md-8 mx-auto">
                <p id="no_reg"> Hello World! Thanks for logging in.</p>
            </div>
        </div>

{% endblock %}

app/templates/macros.html
{% macro nav_link(endpoint, name, link_id, icon) %}
    {% if request.endpoint %}
        {% if request.endpoint.endswith(endpoint) %}
            <li class="nav-item active">
                {% else %}
            <li class="nav-item">
        {% endif %}
    {% else %}
        <li class="nav-item">
    {% endif %}
<a id="{{ link_id }}" class="nav-link" href="{{ url_for(endpoint) }}">
    {% if icon %}
        <i class="{{ icon }} " aria-hidden=true>&nbsp;</i>
    {% endif %}
    {{ name }}
</a></li>
{% endmacro %}
{% macro add_google_analytics(ga_code) %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ ga_code }}"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());
        gtag('config', '{{ ga_code }}');
        {% if not current_user.is_anonymous %}
            gtag('set', {'user_id': '{{ current_user.id }}'}); // Set the user ID using signed-in user_id.
        {%  endif %}
    </script>
{% endmacro %}
{% macro add_support_sidebar() %}
    <nav id="sidebar" class="navbar">
        <ul class="navbar-nav">
            <li class="nav-item"><a href="{{ url_for('support.faq') }}">FAQ</a></li>
            <li class="nav-item"><a href="{{ url_for('support.contact_us') }}">Contact Us</a></li>
            <li class="nav-item"><a href="{{ url_for('support.disclaimer') }}">Disclaimer</a></li>
            <li class="nav-item"><a href="{{ url_for('support.privacy') }}">Privacy Policy</a></li>
            <li class="nav-item"><a href="{{ url_for('support.cookies') }}">Use of Cookies</a></li>
        </ul>
    </nav>
{% endmacro %}

app/templates/support/contact_us.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

        <div class="row">
            <div class="col-md-8 mx-auto">
                <h3 class="h3 mb-3 font-weight-normal">Contact Us</h3>
                <p>We'd love to hear from you. Questions, jokes, feedback on the site, suggested improvements. All are
                    welcome.</p>
                <p>We read and respond to every inquiry. We really do want to hear from you!</p>
                <p>Please fill in the form below</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 mx-auto box-shadow bg-light">
                <form action="{{ form_url }}" method="post" name="hello" novalidate>
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ wtf.form_field(form.name, class="form-control") }}
                        {% for error in form.name.errors %}
                            <small class="form-text text-muted">[{{ error }}]</small>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ wtf.form_field(form.email, class="form-control") }}
                        {% for error in form.email.errors %}
                            <small class="form-text text-muted">[{{ error }}]</small>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ wtf.form_field(form.subject, class="form-control") }}
                        {% for error in form.subject.errors %}
                            <small class="form-text text-muted">[{{ error }}]</small>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        {{ wtf.form_field(form.message, class="form-control", rows=8) }}
                        {% for error in form.message.errors %}
                            <small class="form-text text-muted">[{{ error }}]</small>
                        {% endfor %}
                    </div>
                    <button id="send_message" class="btn btn-lg btn-primary btn-block" type="submit">Send Message
                    </button>
                </form>
            </div>
        </div>
        <div class="row pt-2 my-md-2 pt-md-2">
            <div class="col-md-8 mx-auto">
                <p><i class="fa fa-twitter" aria-hidden="true"></i><a href="https://twitter.com/greendinosaur10">Twitter</a></p>
            </div>
        </div>
{% endblock %}

app/templates/support/cookies.html
{% extends "base.html" %}
{% from "macros.html" import add_support_sidebar with context %}
{% block content %}
    <div class="row justify-content-start">
        <div class="col-3">
            {{ add_support_sidebar() }}
        </div>
        <div class="col">
            <h1>Cookies Policy</h1>

            <p>Last updated: June 08, 2020</p>

            <p>This Cookies Policy explains what Cookies are and how We use them. You should read this policy so You can
                understand what type of cookies We use, or the information We collect using Cookies and how that
                information
                is used. </p>
            <p> Vehicula ipsum a arcu cursus. Sollicitudin ac orci phasellus egestas. Ullamcorper malesuada proin libero
                nunc consequat. Gravida cum sociis natoque penatibus. Sed felis eget velit aliquet sagittis id. Viverra
                tellus in hac habitasse platea dictumst vestibulum. Purus semper eget duis at. Pretium quam vulputate
                dignissim suspendisse in est ante. Velit ut tortor pretium viverra. In dictum non consectetur a. Augue
                lacus viverra vitae congue eu consequat ac. Id leo in vitae turpis. Diam sit amet nisl suscipit
                adipiscing bibendum est ultricies integer. Tortor vitae purus faucibus ornare suspendisse sed nisi.
                Neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Semper viverra nam libero
                justo laoreet sit amet cursus. Pulvinar etiam non quam lacus.</p>

        </div>
    </div>
{% endblock %}

app/templates/support/disclaimer.html
{% extends "base.html" %}
{% from "macros.html" import add_support_sidebar with context %}
{% block content %}
    <div class="row justify-content-start">
        <div class="col-3">
            {{ add_support_sidebar() }}
        </div>
        <div class="col">
            <h1>Disclaimer</h1>

            <p>Last updated: June 08, 2020</p>


            <h1>Disclaimer</h1>
            <p> Vehicula ipsum a arcu cursus. Sollicitudin ac orci phasellus egestas. Ullamcorper malesuada proin libero
                nunc consequat. Gravida cum sociis natoque penatibus. Sed felis eget velit aliquet sagittis id. Viverra
                tellus in hac habitasse platea dictumst vestibulum. Purus semper eget duis at. Pretium quam vulputate
                dignissim suspendisse in est ante. Velit ut tortor pretium viverra. In dictum non consectetur a. Augue
                lacus viverra vitae congue eu consequat ac. Id leo in vitae turpis. Diam sit amet nisl suscipit
                adipiscing bibendum est ultricies integer. Tortor vitae purus faucibus ornare suspendisse sed nisi.
                Neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Semper viverra nam libero
                justo laoreet sit amet cursus. Pulvinar etiam non quam lacus.</p>
            <p>
                Venenatis a condimentum vitae sapien pellentesque. Nunc congue nisi vitae suscipit. Eu volutpat odio
                facilisis mauris sit amet massa vitae. Ornare suspendisse sed nisi lacus sed. Mus mauris vitae ultricies
                leo integer malesuada nunc vel risus. Vel eros donec ac odio. Sagittis eu volutpat odio facilisis mauris
                sit. Lacus sed turpis tincidunt id. Accumsan lacus vel facilisis volutpat est velit egestas dui.
                Ultrices tincidunt arcu non sodales neque sodales. Phasellus egestas tellus rutrum tellus pellentesque
                eu tincidunt. Eget arcu dictum varius duis. Curabitur gravida arcu ac tortor dignissim convallis aenean
                et. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Sed egestas egestas
                fringilla phasellus faucibus scelerisque eleifend donec pretium. Nunc sed velit dignissim sodales ut eu
                sem. Laoreet id donec ultrices tincidunt arcu non sodales. Duis tristique sollicitudin nibh sit. Tempus
                egestas sed sed risus pretium quam vulputate.</p>
        </div>
    </div>
{% endblock %}